version: '3.0'

services:
  nodejs-service:
    image: my-service
    restart: always
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/app/src
      - /usr/app/src/node_modules
    environment:
      - NODE_ENV=development
    command:
      - nodemon
    depends_on:
      - postgres
  postgres:
    build: ./database
    image: my-postgres
    restart: always
    ports:
      - "5000:5000"
